sillsdev/l10nsharp

src/L10NSharp/UI/HowToDistributeDialog.cs
src/L10NSharpTests/L10NSharpTests.csproj

Also fix a directory name capitalization problem in a project file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/1)

Fix "How to Distribute" dialog for Linux (BL-2171)

---

src/L10NSharp/UI/HowToDistributeDialog.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/2)

Fix the fix for showing TMX files in file chooser (Linux/BL-2171)

---

src/L10NSharp/LocalizedStringCache.cs
src/L10NSharpTests/LocalizationManagerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/3)

Fix broken Group tests

---

src/L10NSharpTests/LocalizationManagerTests.cs

.select().any() -> .any()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/5)

Fix Mono test, take 2

---

src/L10NSharp/LocalizedStringCache.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/7)

Added line back in which breaks display of strings in localization dialog

---

build/L10NSharp.proj

This may not do anything, but it's the only lead I have at the moment to get tests working on TC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/12)

Tweak the NUnitTeamCity task definition to match libpalaso's.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/13)

Add Linux information to README.md

---

build/NuGet.targets
src/L10NSharpTests/L10NSharpTests.csproj

I copied the NuGet.targets file from BloomDesktop in case you were wondering about the changes in that file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/15)

Update L10NSharp build to download NuGet packages via msbuild

---

src/L10NSharp/CodeReader/StringExtractor.cs
src/L10NSharp/LocalizedStringCache.cs
src/L10NSharp/TransUnitUpdater.cs
src/L10NSharp/UI/CustomDropDownComboBox.cs
src/L10NSharp/UI/L10NExtender.cs
src/L10NSharp/UI/ShortcutKeysDropDown.cs
src/L10NSharp/UI/Utils.cs
src/L10NSharp/XLiffUtils/TransUnit.cs
src/L10NSharp/XLiffUtils/XLiffBody.cs
src/L10NSharp/XLiffUtils/XLiffDocument.cs
src/L10NSharp/XLiffUtils/XLiffFile.cs
src/L10NSharp/XLiffUtils/XLiffHeader.cs
src/L10NSharp/XLiffUtils/XLiffNote.cs
src/L10NSharp/XLiffUtils/XLiffXmlSerializationHelper.cs
src/L10NSharpTests/L10NSharpTests.csproj
src/L10NSharpTests/LocalizationManagerTests.cs
src/L10NSharpTests/MockLocalizableComponent.cs
src/L10NSharpTests/SchemaValidationTests.cs
src/L10NSharpTests/TestXliff/Test.en.xlf
src/L10NSharpTests/TestXliff/xliff-core-1.2-transitional.xsd
src/L10NSharpTests/XLiffUtilsTests.cs
src/xslt/l10nSharpTmxToXliff1-2.xsl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/16)

Get xliff branch working with Bloom and remove warnings

---

src/L10NSharp/LocalizationManager.cs
src/L10NSharp/LocalizedStringCache.cs
src/L10NSharp/TransUnitUpdater.cs
src/L10NSharp/XLiffUtils/TransUnit.cs
src/L10NSharp/XLiffUtils/XLiffBody.cs
src/L10NSharp/XLiffUtils/XLiffDocument.cs
src/L10NSharp/XLiffUtils/XLiffFile.cs
src/L10NSharp/XLiffUtils/XLiffXmlSerializationHelper.cs
src/L10NSharpTests/LocalizationManagerTests.cs
src/L10NSharpTests/SchemaValidationTests.cs
src/L10NSharpTests/TestXliff/Test.fr.xlf
src/L10NSharpTests/XLiffUtilsTests.cs

Also finish getting new xliff based code to work with Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/17)

Allow folder structure for xliff files

---

src/L10NSharp/CodeReader/StringExtractor.cs
src/L10NSharp/UI/InitializationProgressDlg.cs

This fixes http://issues.bloomlibrary.org/youtrack/issue/BL-4840
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/22)

Fix hanging bug on Linux scanning libpalaso assemblies

---

.gitignore
L10NSharp.sln
src/ExtractXliff/App.config
src/ExtractXliff/ExtractXliff.csproj
src/ExtractXliff/Program.cs
src/ExtractXliff/Properties/AssemblyInfo.cs
src/L10NSharp/CodeReader/StringExtractor.cs
src/L10NSharp/LocalizationManager.cs
src/L10NSharp/LocalizedStringCache.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/26)

Create ExtractXliff command line program

---

src/L10NSharp/L10NCultureInfo.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/29)

Provide valid CurrentCulture when not initialized yet

---

src/L10NSharp/LocalizationManager.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/32)

BL-5272 Add a way to clear disposed managers for unit tests

---

src/L10NSharp/LocalizationManager.cs
src/L10NSharp/TransUnitUpdater.cs
src/L10NSharpTests/LocalizationManagerTests.cs

Also remove a couple of debug output statements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/34)

Handle notes from old xliff during merge

---

src/L10NSharp/TransUnitUpdater.cs
src/L10NSharpTests/LocalizationManagerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/35)

BL-4887 Add Unit test for Newline handling

---

L10NSharp.sln
src/CheckOrFixXliff/App.config
src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/CheckOrFixXliff/Program.cs
src/CheckOrFixXliff/Properties/AssemblyInfo.cs
src/CheckOrFixXliff/xliff-core-1.2-transitional.xsd
src/L10NSharp/LocalizedStringCache.cs
src/L10NSharpTests/L10NSharpTests.csproj
src/L10NSharpTests/LocalizedStringCacheTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/37)

Add CheckOrFixXliff program (BL-5409, BL-5415)

---

src/L10NSharp/LocalizationManager.cs
src/L10NSharp/XLiffUtils/XLiffDocument.cs
src/L10NSharpTests/XLiffUtilsTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/41)

Add flag to return only approved translations (BL-5472)

---

src/L10NSharp/L10NCultureInfo.cs
src/L10NSharp/LocalizationManager.cs
src/L10NSharp/LocalizedStringCache.cs
src/L10NSharpTests/LocalizationManagerTests.cs

Also clean up a few meaningless compilation warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/43)

Allow inexact UI languages for localization (BL-5479)

---

src/L10NSharp/LocalizationManager.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/47)

Prevent undesired L10NSharp dialog for list headers (BL-5935)

---

src/L10NSharp/LocalizationManager.cs

This fixes https://silbloom.myjetbrains.com/youtrack/issue/BL-6146.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/48)

Delete corrupted "default" xliff file instead of crashing

---

src/L10NSharp/LocalizationManager.cs
src/L10NSharpTests/LocalizationManagerTests.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/50)

BL-6449 Complete implementation of FallbackLanguages

---

src/L10NSharp/LocalizationManager.cs
src/L10NSharp/XLiffUtils/TransUnitVariant.cs
src/L10NSharp/XLiffUtils/XLiffXmlSerializationHelper.cs
src/L10NSharpTests/TestXliff/Test2.en.xlf
src/L10NSharpTests/XLiffUtilsTests.cs

Also fix a previously failing test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/54)

Handle embedded HTML markup in Xliff strings (BL-6893)

---

src/L10NSharp/XLiffUtils/XLiffXmlSerializationHelper.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/55)

Reduce noise when loading xliff files from crowdin (20190320)

---

GitVersion.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/57)

Fix version numbers on xliff branch

---

CHANGELOG.md
src/ExtractXliff/ExtractXliff.csproj
src/L10NSharp/L10NSharp-Designer.csproj

Also fix designer project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/58)

 Correct ExtractXliff.dll to ExtractXliff.exe 

---

CHANGELOG.md
src/L10NSharp/L10NSharp.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/65)

Create symbol nuget package

---

CHANGELOG.md
GitVersion.yml
src/L10NSharp/L10NSharp.csproj

Also add company name, copyright etc. to assembly info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/69)

Include build number in AssemblyFileVersion

---

GitVersion.yml
build/L10NSharp.proj
build/NuGet.targets
src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/ExtractXliff/ExtractXliff.csproj
src/L10NSharp/L10NSharp.csproj
src/L10NSharpTests/LanguageChoosingDialogViewModelTests.cs

Also update GitVersionTask.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/70)

Add link to full changelog to package description

---

src/ExtractXliff/Program.cs

* Support filename globs
* Load assemblies with dependencies in the assembly context
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/71)

Improve ExtractXliff to prepare for using in Crowdin automation

---

CHANGELOG.md
build/L10NSharp.proj
src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/CheckOrFixXliff/README.md
src/ExtractXliff/ExtractXliff.csproj
src/ExtractXliff/README.md
src/L10NSharp/L10NSharp.csproj
src/L10NSharpTests/L10NSharpTests.csproj

+semver:minor
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/72)

Add ExtractXliff and CheckOrFixXliff as nuget packages

---

src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/ExtractXliff/ExtractXliff.csproj
src/L10NSharp/L10NSharp.csproj

Also improve symbol package by adding reference to sourcelink.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/73)

Include dependent L10NSharp.dll in tools nuget package

---

src/ExtractXliff/Program.cs
src/L10NSharp/CodeReader/StringExtractor.cs
src/L10NSharp/LocalizationManagerInternal.cs

Used in verbose mode in ExtractXliff

+semver:minor Improved error handling/reporting when loading DLLs using reflection

---

src/L10NSharp/CodeReader/StringExtractor.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/79)

Removed debugging lines that accidentally got committed

---

.gitignore
src/L10NSharp/XLiffUtils/XLiffDocument.cs

This is an attempt to address https://jira.sil.org/browse/HT-378.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/83)

Put in logic to re-attempt save when an IO exception is thrown.

---

CHANGELOG.md
src/L10NSharp/LocalizationManager.cs
src/L10NSharp/LocalizationManagerInternal.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/86)

Provide an option to not throw if LM disposed (BL-9904)

---

.gitignore
L10NSharp.sln
appveyor.yml
build/NuGet.targets
lgtm.yml
src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/ExtractXliff/ExtractXliff.csproj
src/L10NSharp/L10NSharp.csproj
src/L10NSharp/UI/HowToDistributeDialog.Designer.cs
src/L10NSharp/UI/HowToDistributeDialog.cs
src/L10NSharp/UI/HowToDistributeDialog.resx
src/L10NSharp/UI/LocalizeItemDlg.Designer.cs
src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs

Solves https://github.com/sillsdev/l10nsharp/issues/81
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/90)

Fixed overlapping text in How To Distribute dialog; improved internationalization

---

CHANGELOG.md
README.md
src/ExtractXliff/Program.cs
src/L10NSharp/ILocalizationManager.cs
src/L10NSharp/ILocalizedStringCache.cs
src/L10NSharp/LocalizationManagerInternal.cs
src/L10NSharp/TMXUtils/TMXLocalizationManager.cs
src/L10NSharp/TMXUtils/TMXLocalizedStringCache.cs
src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs
src/L10NSharp/XLiffUtils/XLiffTransUnitUpdater.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/91)

Load Xliff files lazily (BL-10843)

---

src/CheckOrFixXliff/CheckOrFixXliff.csproj
src/Directory.Build.props
src/ExtractXliff/ExtractXliff.csproj
src/L10NSharp/L10NSharp.csproj

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/92)

Added property to fix the way versions are published via nuget

---

src/L10NSharp/LocalizationManagerInternal.cs
src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
src/L10NSharpTests/XLiffLocalizationManagerTests.cs
src/SampleApp/Program.cs

.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/98)

Fixed bug: LoadedManagers has wrong AppId because it was passed in with extension during Create

---

CHANGELOG.md
L10NSharp.sln.DotSettings
src/L10NSharp/ILocalizationManager.cs
src/L10NSharp/LocalizationManagerInternal.cs
src/L10NSharp/TMXUtils/TMXLocalizationManager.cs
src/L10NSharp/UI/LocalizeItemDlg.cs
src/L10NSharp/UI/TipDialog.cs
src/L10NSharp/UI/TipDialog.designer.cs
src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs

This causes them to be displayed centered on a parent window (and not appear off-screen).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/100)

Added optional owner parameter to methods that show dialog boxes

---

CHANGELOG.md
src/L10NSharp/CodeReader/StringExtractor.cs
src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/105)

Replace exception rethrow with writing warning message (20221006)

---

.github/workflows/CI-CD.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/106)

Trigger GHA on tag push

---

CHANGELOG.md

Need to release this version to fix PG-1502
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/114)

Added version 7.0.0 in CHANGELOG

---

CHANGELOG.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/124)

Adjusted release date in CHANGELOG.md
