sillsdev/l10nsharp

src/L10NSharpTests/LocalizationManagerTests.cs
Ubuntu Precise does not have 'az' culture. Trusty does.
This test will be ignored on Precise, but will pass correctly on Trusty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/4)
=> Fix mono test

src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTests.cs
This is needed by Bloom to help automate choosing the UI language at
the user's first program startup.  (and possibly later if a user
changes the system UI language)  This could be done by initializing
a LocationManager object and calling its GetUILanguages(true) method,
but that's a lot more expensive.
=> Add static L10NManager.GetAvailableUILanguageTags method (BL-4393)

.editorconfig, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizedStringCache.cs, src/L10NSharpTests/LocalizationManagerTests.cs
This allows getting a string to put in a document in a language that is not the UI language. This was previously possible for "dynamic" strings, but this does it for strings found in code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/10)
=> Add a GetString overload that takes a prioritized list of desired langs

src/L10NSharp/LocalizedStringCache.cs, src/L10NSharp/TransUnitUpdater.cs, src/L10NSharp/XLiffUtils/TransUnit.cs, src/L10NSharp/XLiffUtils/XLiffBaseWithNotesAndProps.cs, src/xslt/l10nSharpTmxToXliff1-2.xsl
Our naming convention usually describes where the string is found in
the user interface, which may be helpful for translators.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/18)
=> Copy the trans-unit id string to a note to make it visible

src/L10NSharp/LocalizedStringCache.cs
This fixes a failing test in Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/19)
=> Check inputs for GetValueForExactLangAndId method

src/L10NSharp/LocalizationManager.cs
I missed this in the big PR a few days ago.  It shows up with dynamic strings not being found from javascript when running Bloom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/20)
=> Fix the DefaultInstalledStringFilePath property to handle folders

src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTests.cs
Previous behavior in this edge case was to return the id, which seems to violate the advertised behavior of the method and does not seem logical. This presumably only affects the behavior when running unit tests, but there's a chance it could also affect an app during startup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/23)
=> Changed logic of GetDynamicStringOrEnglish in when no LMs are loaded so that it returns the English string.

src/L10NSharp/LocalizationManager.cs
This is on the xliff branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/24)
=> Allow 3-letter ISO codes for localization languages

src/L10NSharp/LocalizationManager.cs
This is needed for localizations into minor languages that the system
doesn't know about, and for which Mono won't create CultureInfo objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/25)
=> Provide access to localized language tags

src/L10NSharp/LocalizationManager.cs
This is just an attempt to get more information about a very mysterious bug
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/27)
=> BL-5272 seek more info if wrong LM requested

src/L10NSharp/L10NCultureInfo.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/L10NCultureInfoTests.cs, src/L10NSharpTests/L10NSharpTests.csproj, src/L10NSharpTests/LocalizationManagerTests.cs
We can't depend on CultureInfo working for every language that our
programs may be localized into.  Mono 4 throws exceptions while
.Net 4.6.1 creates generally worthless objects for languages that
the authors didn't know about or didn't consider worth implementing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/28)
=> Handle languages the system doesn't know about (BL-5260)

src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTests.cs
At least in one case, where we're specifically asking for a string from a particular LM, we can report if it has been disposed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/31)
=> BL-5272 Give a better error message for disposed LM

src/L10NSharpTests/L10NCultureInfoTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/30)
=> Fix L10NCultureInfo_TestPbu to pass on Windows

src/ExtractXliff/ExtractXliff.csproj, src/ExtractXliff/Program.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizedStringCache.cs, src/L10NSharp/TransUnitUpdater.cs, src/L10NSharpTests/LocalizationManagerTests.cs
Also move XLiffDocument merging code to LocalizationManager.  The new
code helps in harvesting strings from running a program to verify which
strings in existing xliff files may be outdated and which strings need
to be added or updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/33)
=> Add IgnoreExistingEnglishXliffFiles global flag

src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTests.cs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/36)
=> Prevent redundant OLD NOTE markup during xliff merge

src/CheckOrFixXliff/Program.cs, src/L10NSharp/LocalizedStringCache.cs, src/L10NSharpTests/LocalizedStringCacheTests.cs
1) Write an error message for invalid XML (oops...)
2) Fix substitution markers with improperly translated Bengali numbers
3) Return error code to allow use in scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/38)
=> Improve the CheckOrFixXliff program in several ways

src/L10NSharp/LocalizedStringCache.cs, src/L10NSharpTests/LocalizedStringCacheTests.cs
Translators have made a few more error patterns
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/39)
=> Add more fixup to CheckOrFixXliff

src/L10NSharp/LocalizationManager.cs, src/L10NSharp/XLiffUtils/TransUnit.cs, src/L10NSharp/XLiffUtils/TransUnitVariant.cs, src/L10NSharp/XLiffUtils/XLiffBody.cs, src/L10NSharp/XLiffUtils/XLiffDocument.cs, src/L10NSharpTests/LocalizationManagerTests.cs, src/L10NSharpTests/TestXliff/Test.es.xlf, src/L10NSharpTests/XLiffUtilsTests.cs
The counts include the number of strings, the number of strings that
appear to be translated, and the number of translated strings that
have been approved.  The second two numbers are also available as
fractions at the static LocalizationManager level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/40)
=> Add methods for obtaining translation counts (BL-5472)

src/L10NSharp/LocalizedStringCache.cs
These are really strange because there's no explanation for why
random LTR MARKER characters have been inserted into some strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/42)
=> Fix a few more broken {[0-9]} marker patterns

src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizedStringCache.cs, src/L10NSharpTests/LocalizationManagerTests.cs
Language codes may come from HTML or other sources, not just from
setting the UI language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/44)
=> More inexact language code matching (BL-5479)

src/L10NSharp/LocalizedStringCache.cs
This doesn't fix the reported crash, but does provide more specific information.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/49)
=> Report the filename for a corrupted xlf file (BL-6420)

src/L10NSharp/L10NSharp-Designer.csproj, src/L10NSharp/L10NSharpListExtensions.cs, src/L10NSharp/TMXUtils/TMXLocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTestsBase.cs, src/L10NSharpTests/TMXLocalizationManagerTests.cs
The current 4.0 code is only looking for TMX files in the 'Installed' directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/62)
=> Find TMX files in 'Generated' and 'User Modified' directories

CHANGELOG.md, src/L10NSharp/L10NSharp-Designer.csproj, src/L10NSharp/UI/LanguageChoosingDialog.cs, src/L10NSharp/UI/LanguageChoosingDialogViewModel.cs, src/L10NSharpTests/LanguageChoosingDialogViewModelTests.cs
Fix for https://github.com/sillsdev/l10nsharp/issues/66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/67)
=> Avoid having Bing mis-translate native UI language name back as "English"

CHANGELOG.md, src/L10NSharp/UI/LanguageChoosingDialog.cs, src/L10NSharp/UI/LanguageChoosingDialogViewModel.cs, src/L10NSharpTests/LanguageChoosingDialogViewModelTests.cs
If translator returns an unmodified source string, don't substitute t…he English language name for the vernacular name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/68)
=> In LanguageChoosingDialog, handle off-line case where translator just returns source string

CHANGELOG.md, src/ExtractXliff/Program.cs, src/L10NSharp/CodeReader/StringExtractor.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharp/TMXUtils/TMXLocalizationManager.cs, src/L10NSharp/UI/InitializationProgressDlg.cs, src/L10NSharp/UI/InitializationProgressDlgBase.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, src/L10NSharpTests/LocalizationManagerTestsBase.cs, src/L10NSharpTests/ProxyLocalizationManager.cs, src/L10NSharpTests/TMXLocalizationManagerTests.cs, src/L10NSharpTests/XLiffLocalizationManagerTests.cs, src/SampleApp/Program.cs
This allows the client to specify additional localization methods when extracting from code. Useful, for example, when using SIL.Localizer to allow L10nSharp to be injected in code that does not depend on it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/75)
=> Added version of LocalizationManager.Create with param to allow additional GetString methods

CHANGELOG.md, src/ExtractXliff/Program.cs
This allows us to harvest strings from non Windows.Forms assemblies in libpalaso (that can't reference L10nSharp) but that use the SIL.Localizer class as a proxy.
=> PG-1365: Enhanced ExtractXliff tool to be able to specify additional methods

src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharpTests/LocalizationManagerXliffTests.cs, src/L10NSharpTests/TestXliff2/Test.en.xlf, src/L10NSharpTests/TestXliff2/Test.es.xlf, src/L10NSharpTests/TestXliff2/Test.pt.xlf
For programs that are switching from TMX-based localization to XLIFF-based, languages like Spanish (es) and Portuguese (pt) will typically use a langiage code that includes a country specifier (es-ES, pt-PT). The LocalizationManager already knows about these mappings and handles them ocrrectly when getting strings, but not when checking to see if the requested UI language is available.
If the caller requests a desired UI based on a two-letter language code that is not available, but there is a mapping to the corresponding (country-)specifiic locale, use that without displaying the "UI not available" dialog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/78)
=> Create LocalizationManager using more specific locale if necessary

src/L10NSharp/CodeReader/StringExtractor.cs
This is currently killing Bloom on the master branch on Linux.  And
Bloom doesn't even care that much about the automatic scanning!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/80)
=> Fix a crashing bug inside L10NSharp scanning

L10NSharp.sln.DotSettings, src/L10NSharp/CodeReader/StringExtractor.cs, src/L10NSharp/UI/InitializationProgressDlg.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
Don't cause a crash by generating a zero-length file.
Provide a mechanism by which the developer can get the root cause of extraction errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/85)
=> Improve error handling

Directory.Build.targets, README.md, src/L10NSharp/UI/InitializationProgressDlg.cs
If the result of extracting strings is null or the wrong type,
or if some other exception occurs, report it in the localizations
file. This gives developers information and prevents crashes later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/87)
=> Generate messages for all extraction errors

CHANGELOG.md, src/L10NSharp/TMXUtils/TMXLocalizationManager.cs, src/L10NSharp/UI/LocalizeItemDlg.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
This is to address HT-417. It allows the consumer of the StringsLocalized event to respond appropriately based on the LocalizationManager (and avoid responding more than once if the application creates more than one LM).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/89)
=> +semver:major Added ILocalizationManager parameter to StringsLocalizedHandler

L10NSharp.sln.DotSettings, src/L10NSharp/CodeReader/StringExtractor.cs
Should be reported but can be safely ignored when trying to load the instructions of a method in order to get the method calls it contains.
This fixes a problem in HearThis that causes the extracting to prematurely abort when loading strings for Palaso.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/94)
=> Added BadImageFormatException to the list of exceptions to ignore

CHANGELOG.md, README.md, src/CheckOrFixXliff/Program.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharp/TMXUtils/TMXLocalizedStringCache.cs, src/L10NSharp/XLiffUtils/XLiffBody.cs, src/L10NSharp/XLiffUtils/XLiffDocument.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs, src/L10NSharp/XLiffUtils/XLiffTransUnitUpdater.cs, src/L10NSharpTests/XLiffLocalizationManagerTests.cs
Also makes all methods consistently handle fall-back from e.g. es-BR to es-ES.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/93)
=> Make lazy loading of xliffs thread-safe (BL-11086)

CHANGELOG.md, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
This was discussed at the conference.  I think this is the minimal
change to the code that allows current behavior for programs that may
still benefit from it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/95)
=> Remove progress dialogs for xliff initialization

src/L10NSharp/TMXUtils/TMXXmlSerializationHelper.cs, src/L10NSharp/UI/LocalizeItemDlg.cs, src/L10NSharp/UI/LocalizeItemDlgViewModel.cs, src/SampleApp/Form1.Designer.cs, src/SampleApp/Form1.cs
When changes are made in the localization dialog, the StringsLocalized gets fired for all managers that have had their strings modified for the current UI language.
Also made a couple small improvements to the SampleApp so that is it more useful for testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/96)
=> SP-2269: Made StringsLocalized fire for each modified LocalizatinoManager

CHANGELOG.md, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs, src/L10NSharpTests/XLiffLocalizationManagerTests.cs
Also, changed to use Id rather than Name to generate the "original" attribute in XLIFF files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/97)
=> Allow caller to specify file extension of the "original" executable file in LocalizationManager.Create

.github/workflows/CI-CD.yml, CHANGELOG.md, L10NSharp.sln, src/CheckOrFixXliff/CheckOrFixXliff.csproj, src/ExtractXliff/ExtractXliff.csproj, src/L10NSharp/L10NSharp.csproj, src/L10NSharp/LocalizationManager.cs, src/L10NSharpTests/ILocalizableComponentTests.cs, src/L10NSharpTests/L10NSharpTests.csproj, src/L10NSharpTests/LocalizationManagerXliffTests.cs, src/SampleApp/Program.cs
Also deprecate existing `Create` methods with `kind` parameter. 
Since `Xliff` is now the only supported translation memory, the `kind` parameter is unnecessary. This change adds new overloads without the `kind` parameter and marks the existing methods as `Obsolete`. 
+semver:minor
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/107)
=> Add `LocalizationManager.Create` methods without `kind` parameter

src/L10NSharp/CodeReader/StringExtractor.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs
Changed several Console.WriteLine calls to use Trace.WriteLine in hopes that we will get better information in log files when errors occur.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/112)
=> Added FileLoadException to the list of ignorable errors in FindLocalizedStringsInType

CHANGELOG.md, L10NSharp.sln, README.md, src/CheckOrFixXliff/Program.cs, src/ExtractXliff/Program.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharp/XLiffUtils/XLiffBody.cs, src/L10NSharp/XLiffUtils/XLiffLocalizationManager.cs, src/L10NSharp/XLiffUtils/XLiffLocalizedStringCache.cs, src/L10NSharp/XLiffUtils/XLiffTransUnitUpdater.cs, src/L10NSharpTests/LocalizationManagerTestsBase.cs, src/L10NSharpTests/XLiffLocalizedStringCacheTests.cs
If a client tries to initialize a LocalizationManager with only
a language code, and we have a language available with that code
plus extra information, use that language without prompting the user.
Previous behavior: prompted the user with a dialog in this case.
Unchanged behavior: initializing with extra information will fall back to the bare language code.
This addresses https://github.com/sillsdev/l10nsharp/issues/109
This addresses https://jira.sil.org/browse/LT-21232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="44" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/110)
=> [API] #109: find specific languages when generics are specified

src/ExtractXliff/Program.cs, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharp/XLiffUtils/XLiffDocument.cs, src/L10NSharp/XLiffUtils/XLiffFile.cs, src/L10NSharp/XLiffUtils/XLiffTransUnit.cs, src/L10NSharp/XLiffUtils/XLiffTransUnitVariant.cs, src/L10NSharp/XLiffUtils/XliffLocalizationManager.cs, src/L10NSharp/XLiffUtils/XliffLocalizedStringCache.cs, src/L10NSharp/XLiffUtils/XliffTransUnitUpdater.cs, src/L10NSharp/XLiffUtils/XliffXmlSerializationHelper.cs, src/L10NSharpTests/XLiffLocalizationManagerTests.cs
fixing public capitalization would be breaking,
and writing deprecation shims for each could consume time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/111)
=> Fix capitalization on internal XliffUtils classes

CHANGELOG.md, src/L10NSharp/LocalizationManager.cs, src/L10NSharp/LocalizationManagerInternal.cs, src/L10NSharpTests/LocalizationManagerTestsBase.cs, src/L10NSharpTests/LocalizationManagerTests_NoManagersLoaded.cs, src/L10NSharpTests/XLiffLocalizationManagerTests.cs
+semver: major
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/120)
=> Throw if the library is used before being initialized (BL-13266)

.github/workflows/CI-CD.yml, Directory.Build.props, src/CheckOrFixXliff/CheckOrFixXliff.csproj, src/CheckOrFixXliff/Program.cs, src/ExtractXliff/ExtractXliff.csproj, src/L10NSharp/L10NCultureInfo.cs, src/L10NSharp/L10NSharp.csproj, src/L10NSharpTests/L10NCultureInfoTests.cs, src/L10NSharpTests/L10NSharpTests.csproj, src/L10NSharpTests/TempFile.cs, src/L10NSharpTests/XLiffSchemaValidationTests.cs, src/SampleApp/SampleApp.csproj
This required platform-specific references in the project files. I also fixed a warning about Assembly.CodeBase and some .NET8 warnings about manually copying duplicate files into our nuget package folder when packing. These files appear to be duplicates of what is copied during the .NET8 packaging.
The only other change worth noting involves the "unknown language" detection in L10nCultureInfo. It appears, per [the link listed in the comment](https://stackoverflow.com/a/71388328/1964319) at that point in the code, that our method of determining an unknown language no longer works, starting with Win10 (combined with .NET). The change I made should be compatible with older OS's, like Win7, but I don't have an easy way to confirm this.
- - -
This change is [<img …
=> Adding Framework 4.8 and .NET8 to targets.

.gitignore, src/SampleApp/Program.cs, src/SampleApp/SampleApp.csproj
Added some test code to the sample app to try to re-create and diagnose problem the Bloom team encountered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/117)
=> Added IncludeSourceRevisionInInformationalVersion to SampleApp so Version doesn't get added garbage

.github/workflows/CI-CD.yml
This should avoid build failure caused by using a deprecated version
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/l10nsharp/123)
=> Upgraded Github actions to v. 4
